site_name: caffeine.bot

repo_url: https://github.com/birb-studio/caffeine.bot
edit_uri: edit/docs/

theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  logo: assets/logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode